default_platform(:ios)

platform :ios do
  desc "Executa todos os testes"
  lane :tests do
    run_tests(scheme: "TEMFC")
  end
  
  desc "Executa testes de UI"
  lane :ui_tests do
    run_tests(scheme: "TEMFC", only_testing: "TEMFCUITests")
  end
  
  desc "Executa testes unitários"
  lane :unit_tests do
    run_tests(scheme: "TEMFC", only_testing: "TEMFCTests")
  end
end